package exception4.log3;

public class Main {
    public static void main(String[] args) {
        Task1.second();
    }
}